---
spring:
  application:
    name: compute-service
  profiles: EurekaClient1
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
---
spring:
  application:
    name: compute-service
  profiles: EurekaClient2
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
