spring:
  application:
    name: API-Gateway
  cloud:
    config:
      uri:
      profile: production
      #label: master
      discovery:
              enabled: true
              service-id: Configuration-Service
server:
  port: 7000
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: Compute-Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
