spring:
  application:
    name: API-Gateway
  cloud:
    config:
      uri:
      profile: production
      #label: master
      discovery:
              enabled: true
              service-id: Configuration-Center
server:
  port: 7000
zuul:
  routes:
    search:
      path: /search/**
      serviceId: LoadBalance-Service
    suggest:
      path: /suggest/**
      serviceId: LoadBalance-Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration-center:9000/eureka/
