spring:
  application:
    name: GetConfig
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/