spring:
  application:
    name: LoadBalance-Service
  cloud:
    config:
      uri:
      profile: production
      #label: master
      discovery:
              enabled: true
              service-id: Configuration-Center
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration-center:9000/eureka/
