spring:
  application:
    name: Search-Service
  cloud:
    config:
      uri:
      profile: production
      #label: master
      discovery:
              enabled: true
              service-id: Configuration-Center
server:
  port: 6000
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration-center:9000/eureka/
  instance:
      lease-expiration-duration-in-seconds: 10
      lease-renewal-interval-in-seconds: 1