spring:
  application:
    name: Suggest-Service
  cloud:
    config:
      uri:
      profile: production
      #label: master
      discovery:
              enabled: true
              service-id: Configuration-Center
server:
  port: 4000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
