---
spring:
  profiles: EurekaServer1
server:
  port: 8000
eureka:
  client:
    # register-with-eureka: false
    # fetch-registry: false
    service-url:
          defaultZone: http://eurekaserver2:8001/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: eurekaserver1

---
spring:
  profiles: EurekaServer2
server:
  port: 8001
eureka:
  client:
    # register-with-eureka: false
    # fetch-registry: false
    service-url:
          defaultZone: http://eurekaserver1:8000/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: eurekaserver2