---
spring:
  profiles: EurekaServer1
server:
  port: 8000
eureka:
  client:
    # register-with-eureka: false
    # fetch-registry: false
    service-url:
          defaultZone: http://localhost:8001/eureka/
  server:
    enable-self-preservation: false
  instance:
    appname: EurekaServer

---
spring:
  profiles: EurekaServer2
server:
  port: 8001
eureka:
  client:
    # register-with-eureka: false
    # fetch-registry: false
    service-url:
          defaultZone: http://localhost:8000/eureka/
  server:
    enable-self-preservation: false
  instance:
    appname: EurekaServer