spring:
  application:
    name: APIGateway
server:
  port: 8050
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: COMPUTE-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/