server:
  port: 8030
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/izhangzhihao/Spring-Cloud/
          username: izhangzhihao
          password: 11111111111111
          search-paths: ConfigRepo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
