server:
  port: 8030
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/izhangzhihao/Spring-Cloud/
          username: izhangzhihao
          password: ******
          search-paths: ConfigRepo
