server:
  port: 8000
spring:
  application:
    name: Configuration-Center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/izhangzhihao/Spring-Cloud-Microservices/
          search-paths: ConfigRepo
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration-center:9000/eureka/